name: app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  dio: ^5.4.3+1
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.1
  video_player: ^2.8.6
  chewie: ^1.8.1
  webview_flutter: ^4.8.0
  easy_refresh: ^3.4.0
  fluro: ^2.0.5
  shared_preferences: ^2.2.3
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  flutter_inappwebview: ^5.8.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.1.2
  provider: ^6.1.2
  photo_view: ^0.15.0
  wechat_assets_picker: ^9.1.0
  extended_image: ^8.2.1
  modal_bottom_sheet: ^3.0.0
  flutter_native_splash: ^2.4.0
  card_swiper: ^3.0.1
  url_launcher: ^6.3.0
  event_bus: ^2.0.0
  video_plugin:
    path: video_plugin
  fijkplayer: ^0.11.0
  flutter_gen: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.6.0

flutter:
  uses-material-design: true
  assets:
    #加载目录下的所有文件
    - assets/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/2.png
  android: true
